### ISSUE TITLE
Change .es to .es6 or just .js

### ISSUE THREAD

**Issue by ghost** [cognitom/ikki#2]
GitHub thinks .es files are Erlang files, so it can be confusing to people looking at the project at first.

Just a suggestion. Nice project @cognitom

**Comment by cognitom** [comment]
@bucaran thanks for your feedback. I was wondering the same thing. `.js` seems better.

**Comment by ghost** [comment]
Erlang's deep purple does look pretty cool though, but as you can see if you browse your files in GitHub the coloring is incorrect.

**Comment by cognitom** [comment]
OK, I've changed the extensions :)
https://github.com/cognitom/ikki/tree/master/lib
