### ISSUE TITLE
Route Transition / Mounting

### ISSUE THREAD

**Issue by ProbablePrime** [cognitom/ikki#7]
I'm using ikki mostly for its awesome router in a small project.

While speed is usually a good thing when it involves navigation its sometimes helpful to provide some sort of transition process to a next page or section.

I did find https://github.com/sartaj/riot-animate but this relies on the routed tags being mounted and unmounted on a route change.

Do you have any thoughts on how I might achieve something smiliar this but still keeping with the ikki style and router?

**Comment by cognitom** [comment]
@ProbablePrime sorry for my late reply.
Ikki depends on `if` attributes of Riot.js, but this has some problems. At this point, the tag will mount even when `if` gets falsy values. This behaviour could cause the issue with such a library like `riot-animate`.
Hopefully the next version of Riot.js would solve the issue. Keep eyes on that ;-)

**Comment by ProbablePrime** [comment]
@cognitom Thanks for the explanation. I'll look out for it! :D
